// <auto-generated />
using System;
using BootShop.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BootShop.DataAccess.Migrations
{
    [DbContext(typeof(bootShopDbContext))]
    [Migration("20220411022338_upd")]
    partial class upd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BootShop.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Telefon"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Laptop"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Tablet"
                        });
                });

            modelBuilder.Entity("BootShop.Entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double?>("Discount")
                        .HasColumnType("double precision");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryId = 1,
                            Discount = 0.5,
                            ImageUrl = "https://productimages.hepsiburada.net/s/49/222-222/10986386391090.jpg/format:webp",
                            Name = "İphone 11",
                            Price = 13000.0
                        },
                        new
                        {
                            ID = 2,
                            CategoryId = 1,
                            Discount = 0.5,
                            ImageUrl = "https://productimages.hepsiburada.net/s/41/222-222/10698988716082.jpg/format:webp",
                            Name = "Samsung Note 20",
                            Price = 13000.0
                        },
                        new
                        {
                            ID = 3,
                            CategoryId = 1,
                            Discount = 0.5,
                            ImageUrl = "https://productimages.hepsiburada.net/s/131/222-222/110000082286300.jpg/format:webp",
                            Name = "Xiomi Mi 11",
                            Price = 13000.0
                        },
                        new
                        {
                            ID = 4,
                            CategoryId = 1,
                            Discount = 0.5,
                            ImageUrl = "https://productimages.hepsiburada.net/s/73/222-222/110000014912740.jpg/format:webp",
                            Name = "Oppo Reno 5",
                            Price = 13000.0
                        },
                        new
                        {
                            ID = 5,
                            CategoryId = 1,
                            Discount = 0.5,
                            ImageUrl = "https://productimages.hepsiburada.net/s/79/222-222/110000021519477.jpg/format:webp",
                            Name = "Samsung A52",
                            Price = 13000.0
                        },
                        new
                        {
                            ID = 6,
                            CategoryId = 2,
                            Discount = 0.5,
                            ImageUrl = "https://productimages.hepsiburada.net/s/131/222-222/110000082171384.jpg/format:webp",
                            Name = "MSİ Gaming",
                            Price = 13000.0
                        },
                        new
                        {
                            ID = 7,
                            CategoryId = 2,
                            Discount = 0.5,
                            ImageUrl = "https://productimages.hepsiburada.net/s/49/222-222/10983950254130.jpg/format:webp",
                            Name = "Macbook Air M1",
                            Price = 13000.0
                        },
                        new
                        {
                            ID = 8,
                            CategoryId = 2,
                            Discount = 0.5,
                            ImageUrl = "https://productimages.hepsiburada.net/s/77/222-222/110000018961471.jpg/format:webp",
                            Name = "Thinkpad X1",
                            Price = 13000.0
                        },
                        new
                        {
                            ID = 9,
                            CategoryId = 2,
                            Discount = 0.5,
                            ImageUrl = "https://productimages.hepsiburada.net/s/42/222-222/10740711587890.jpg/format:webp",
                            Name = "Dell XPS 15",
                            Price = 13000.0
                        },
                        new
                        {
                            ID = 10,
                            Discount = 0.5,
                            ImageUrl = "https://productimages.hepsiburada.net/s/176/222-222/110000140392350.jpg/format:webp",
                            Name = "Huawei Matebook D15",
                            Price = 13000.0
                        },
                        new
                        {
                            ID = 11,
                            CategoryId = 2,
                            Discount = 0.5,
                            ImageUrl = "https://productimages.hepsiburada.net/s/49/222-222/10983950254130.jpg/format:webp",
                            Name = "Macbook Air M1",
                            Price = 13000.0
                        },
                        new
                        {
                            ID = 12,
                            CategoryId = 2,
                            Discount = 0.5,
                            ImageUrl = "https://productimages.hepsiburada.net/s/77/222-222/110000018961471.jpg/format:webp",
                            Name = "Thinkpad X1",
                            Price = 13000.0
                        });
                });

            modelBuilder.Entity("BootShop.Entities.Product", b =>
                {
                    b.HasOne("BootShop.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BootShop.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
